test: don't run tests on Windows PyPy-3.9
It's always failing with:

```
---------------------------- Captured stdout setup ----------------------------
  Processing c:\users\runneradmin\appdata\local\temp\pytest-of-runneradmin\pytest-0\popen-gw1\venv_world0\third_pkg
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Processing d:\a\coveragepy\coveragepy
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 3221226505
    ╰─> [10 lines of output]
        running egg_info
        writing coverage.egg-info\PKG-INFO
        writing dependency_links to coverage.egg-info\dependency_links.txt
        writing entry points to coverage.egg-info\entry_points.txt
        writing requirements to coverage.egg-info\requires.txt
        writing top-level names to coverage.egg-info\top_level.txt
        reading manifest file 'coverage.egg-info\SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        no previously-included directories found matching 'doc\_build'
        no previously-included directories found matching 'doc\_spell'
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
```

3221226505 is:

```
<Yhg1s> nedbat: it was killed with SIGKILL. (exit code 3221226505 is -1073740791, which is 'killed with signal 9')
<Yhg1s> (according to os.WIFSIGNALED() and os.WTERMSIG())
```