refactor(test): make traceback checks a bit flexible
Python 3.11 made a traceback look like this:

    Traceback (most recent call last):
      File "{path}", line 8, in <module>
        print(sys.argv[1])
              ~~~~~~~~^^^
    IndexError: list index out of range

We needed to not care if that tilde-caret line was present or not.