fix: Handle ast.Match not defined in Python 3.10.0-alpha.1
Coverage 7.0.2 introduced some logic relying on ast.Match
which a check that the Python version is 3.10 or more
(see https://github.com/nedbat/coveragepy/commit/cceadff1d3d33c046042b606d40e01f41e23ec5d )

Unfortunately, on version 3.10.0-alpha.1, ast.Match does not
seem to be defined, leading to uncaught exception:
  AttributeError: module 'ast' has no attribute 'Match'

More details can be found on https://github.com/SylvainDe/DidYouMean-Python/issues/59 .

The quickfix is to perform a more precise check on the
Python version (another option could be to try to
access ast.Match and catch the exception).